server:
  port: 8082

jasypt:
  encryptor:
    password: bl123456  

spring:
  datasource:
    url: jdbc:mysql://192.168.4.203:3306/td_portal?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: poly2017
    driver-class-name: com.mysql.cj.jdbc.Driver
    
    hikari:
      pool-name: user_hikari
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000 
      connection-timeout: 30000 
      connection-test-query: SELECT 1