server:
  port: 8081
  
jasypt:
  encryptor:
    password: bl123456
  
spring:
  application:
    name: luis-cloud-oauth
       
  redis:
    host: ENC(qn5/FvkOOxPVjgxgjwOzWfk/RIlfyY2z)
    port: ENC(HSEupnqpzeqv+0W0FtDjTw==)
    password: ENC(C1jcqtmX2PnVrAqaf9kfKEFhErLxf5YG)
    database: 10
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000
      shutdown-timeout: 100

